import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { PomodoroProvider } from "@/app/lib/pomodoro/PomodoroProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Render the app shell and global navigation.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b border-zinc-200 bg-white transition-shadow duration-200 hover:shadow-sm dark:border-zinc-800 dark:bg-black dark:hover:shadow-zinc-900/50">
          <div className="mx-auto flex w-full max-w-5xl items-center gap-4 px-4 py-3 sm:px-6">
            <Link
              href="/"
              className="rounded-md px-2.5 py-1 text-sm font-semibold text-zinc-900 transition-colors duration-150 hover:bg-zinc-50 hover:text-zinc-700 dark:text-zinc-50 dark:hover:bg-zinc-950 dark:hover:text-zinc-200"
            >
              NamehAmal
            </Link>
            <nav className="ml-auto flex items-center gap-2">
              <Link
                href="/"
                className="rounded-md px-2.5 py-1 text-sm text-zinc-700 transition-colors duration-150 hover:bg-zinc-50 hover:text-zinc-900 dark:text-zinc-300 dark:hover:bg-zinc-950 dark:hover:text-zinc-100"
              >
                Dashboard
              </Link>
              <Link
                href="/pomodoro"
                className="rounded-md px-2.5 py-1 text-sm text-zinc-700 transition-colors duration-150 hover:bg-zinc-50 hover:text-zinc-900 dark:text-zinc-300 dark:hover:bg-zinc-950 dark:hover:text-zinc-100"
              >
                Pomodoro
              </Link>
              <Link
                href="/settings"
                className="rounded-md px-2.5 py-1 text-sm text-zinc-700 transition-colors duration-150 hover:bg-zinc-50 hover:text-zinc-900 dark:text-zinc-300 dark:hover:bg-zinc-950 dark:hover:text-zinc-100"
              >
                Settings
              </Link>
              <Link
                href="/stats"
                className="rounded-md px-2.5 py-1 text-sm text-zinc-700 transition-colors duration-150 hover:bg-zinc-50 hover:text-zinc-900 dark:text-zinc-300 dark:hover:bg-zinc-950 dark:hover:text-zinc-100"
              >
                Stats
              </Link>
            </nav>
          </div>
        </header>
        <PomodoroProvider>{children}</PomodoroProvider>
      </body>
    </html>
  );
}
